// This is a manifest file that'll be compiled into including all the files listed below.
// Add new JavaScript/Coffee code in separate files in this directory and they'll automatically
// be included in the compiled file accessible from http://example.com/assets/application.js
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// the compiled file.
//
//= require jquery
//= require jquery_ujs
//= require_tree .


function change_to_menu_stockgroups(){
  $('div.stocktype_container').hide();
  $('div.stockgroup_container').fadeIn(150)
}

function change_to_menu_stocktypes( group ){
  $('div.stockgroup_container').fadeOut(80)
  $('div.stocktype_container#' + group).fadeIn(150);
}

function close_menus(){
  $('div.stocktype_container').fadeOut(80)
  $('div.stockgroup_container').fadeOut(80)
  $("div.custom_entry").remove()
}

function is_in_list(){
  

}


function submit_new_item_for( list, name, group ){
  close_menus();
  if( !is_in_list(name) )
  $.ajax({
    type: "POST",
    url: "/add?list=" + list + "&name=" + name + "&group=" + group, 
    success: function (msg) {
        if( list == "needed_items" ){ 
          // check if an actual key was returned or just an empty string. in case of a key the item was added to the data store on the server side
          // so thus also add it here using javascript to stay in sync.
          if( msg ){
            $("#needed_items").append( $(
            '<div id=id'+ msg + '> <div class="item"> &nbsp;' + name + ' <img src="images/x.png" border=0 class="destroy_button" height=60 width=60 onclick="delete_item(\'' + msg + '\')"> </div> <div class="spacer"> </div> </div>' ) )
          } else {
            alert("Item already present" )
          }
        }
        if( list == "needed_stocktypes" ){
          $("#stocktype_block_"+group).append( $(
            ' <div class="stocktype" id="stocktype_container" onclick=" submit_new_item_for(\'needed_items\',\'' + name + '\',\'' + group + '\')"> &nbsp; ' + name + '</div>'
          ) )
        }
    }


  });
}

function delete_item( id ){
  $("div#id" + id).fadeOut(200, function() { $(this).remove() } );
  $.ajax({
    type: "POST",
    url: "/delete?id=" + id ,
    success: function (msg) { }
  });
}

function do_custom_entry( group ){
  close_menus()
    
  // Create the custom enetry box: 

  custom_entry_box = $( '<div style="display:none" class="custom_entry"> <div id="custom_entry_title">Add ' + group + ' item:</div> <form id="add_custom_item_form" > <input type="text" name="field" class="custom_item" id="custom_item"/> </form> </div> ' )
  custom_entry_box.submit( 
    function() {
      submit_custom_entry( group )
      return false;
    });
  $("body").append(custom_entry_box)
  $("div.custom_entry").fadeIn(200, function() {} );

}

function match_words( str, list ){
 for (word in list) {
  if( str.match(new RegExp(list[word],'i')) ){ return true; }
 }
 return false;
}


function submit_custom_entry( group ){
  console.log( "submit_custom_entry: " + $("#custom_item").val() )
  console.log( "submit_custom_entry: group: " +  group )
  item_name =  $("#custom_item").val()

  // Ellery filter
  // check item_name against swearwords 
  if( match_words( item_name, profanity ) ){
    alert("Why the profanity? Please try and be more polite. Thank you. ")
  } else {
    // trigger addition to shopping list
    submit_new_item_for("needed_items", item_name, group )

    // trigger addition to stocktype list (unless item already exists)
    submit_new_item_for("needed_stocktypes", item_name, group )
  }

  close_menus() 
}

profanity = ["ahole",
"anus",
"ash0le",
"ash0les",
"asholes",
"ass",
"Ass Monkey",
"Assface",
"assh0le",
"assh0lez",
"asshole",
"assholes",
"assholz",
"asswipe",
"azzhole",
"bassterds",
"bastard",
"bastards",
"bastardz",
"basterds",
"basterdz",
"Biatch",
"bitch",
"bitches",
"Blow Job",
"boffing",
"butthole",
"buttwipe",
"c0ck",
"c0cks",
"c0k",
"Carpet Muncher",
"cawk",
"cawks",
"Clit",
"cnts",
"cntz",
"cock",
"cockhead",
"cock-head",
"cocks",
"CockSucker",
"cock-sucker",
"crap",
"cum",
"cunt",
"cunts",
"cuntz",
"dick",
"dild0",
"dild0s",
"dildo",
"dildos",
"dilld0",
"dilld0s",
"dominatricks",
"dominatrics",
"dominatrix",
"dyke",
"enema",
"f u c k",
"f u c k e r",
"fag",
"fag1t",
"faget",
"fagg1t",
"faggit",
"faggot",
"fagit",
"fags",
"fagz",
"faig",
"faigs",
"fart",
"flipping the bird",
"fuck",
"fucker",
"fuckin",
"fucking",
"fucks",
"Fudge Packer",
"fuk",
"Fukah",
"Fuken",
"fuker",
"Fukin",
"Fukk",
"Fukkah",
"Fukken",
"Fukker",
"Fukkin",
"g00k",
"gay",
"gayboy",
"gaygirl",
"gays",
"gayz",
"God-damned",
"h00r",
"h0ar",
"h0re",
"hells",
"hoar",
"hoor",
"hoore",
"jackoff",
"jap",
"japs",
"jerk-off",
"jisim",
"jiss",
"jizm",
"jizz",
"knob",
"knobs",
"knobz",
"kunt",
"kunts",
"kuntz",
"Lesbian",
"Lezzian",
"Lipshits",
"Lipshitz",
"masochist",
"masokist",
"massterbait",
"masstrbait",
"masstrbate",
"masterbaiter",
"masterbate",
"masterbates",
"Motha Fucker",
"Motha Fuker",
"Motha Fukkah",
"Motha Fukker",
"Mother Fucker",
"Mother Fukah",
"Mother Fuker",
"Mother Fukkah",
"Mother Fukker",
"mother-fucker",
"Mutha Fucker",
"Mutha Fukah",
"Mutha Fuker",
"Mutha Fukkah",
"Mutha Fukker",
"n1gr",
"nastt",
"nigger;",
"nigur;",
"niiger;",
"niigr;",
"orafis",
"orgasim;",
"orgasm",
"orgasum",
"oriface",
"orifice",
"orifiss",
"packi",
"packie",
"packy",
"paki",
"pakie",
"paky",
"pecker",
"peeenus",
"peeenusss",
"peenus",
"peinus",
"pen1s",
"penas",
"penis",
"penis-breath",
"penus",
"penuus",
"Phuc",
"Phuck",
"Phuk",
"Phuker",
"Phukker",
"polac",
"polack",
"polak",
"Poonani",
"pr1c",
"pr1ck",
"pr1k",
"pusse",
"pussee",
"pussy",
"puuke",
"puuker",
"queer",
"queers",
"queerz",
"qweers",
"qweerz",
"qweir",
"recktum",
"rectum",
"retard",
"sadist",
"scank",
"schlong",
"screwing",
"semen",
"sex",
"sexy",
"Sh!t",
"sh1t",
"sh1ter",
"sh1ts",
"sh1tter",
"sh1tz",
"shit",
"shits",
"shitter",
"Shitty",
"Shity",
"shitz",
"Shyt",
"Shyte",
"Shytty",
"Shyty",
"skanck",
"skank",
"skankee",
"skankey",
"skanks",
"Skanky",
"slut",
"sluts",
"Slutty",
"slutz",
"son-of-a-bitch",
"tit",
"turd",
"va1jina",
"vag1na",
"vagiina",
"vagina",
"vaj1na",
"vajina",
"vullva",
"vulva",
"w0p",
"wh00r",
"wh0re",
"whore",
"xrated",
"xxx",
"b!+ch",
"bitch",
"blowjob",
"clit",
"arschloch",
"fuck",
"shit",
"ass",
"asshole",
"b!tch",
"b17ch",
"b1tch",
"bastard",
"bi+ch",
"boiolas",
"buceta",
"c0ck",
"cawk",
"chink",
"cipa",
"clits",
"cock",
"cum",
"cunt",
"dildo",
"dirsa",
"ejakulate",
"fatass",
"fcuk",
"fuk",
"fux0r",
"hoer",
"hore",
"jism",
"kawk",
"l3itch",
"l3i+ch",
"lesbian",
"masturbate",
"masterbat",
"masterbat3",
"motherfucker",
"s.o.b.",
"mofo",
"nazi",
"nigga",
"nigger",
"nutsack",
"phuck",
"pimpis",
"pusse",
"pussy",
"scrotum",
"sh!t",
"shemale",
"shi+",
"sh!+",
"slut",
"smut",
"teets",
"tits",
"boobs",
"b00bs",
"teez",
"testical",
"testicle",
"titt",
"w00se",
"jackoff",
"wank",
"whoar",
"whore",
"damn",
"dyke",
"fuck*",
"shit*",
"@$$",
"amcik",
"andskota",
"arse",
"assrammer",
"ayir",
"bi7ch",
"bitch",
"bollock",
"breasts",
"butt-pirate",
"cabron",
"cazzo",
"chraa",
"chuj",
"Cock",
"cunt",
"d4mn",
"daygo",
"dego",
"dick",
"dike",
"dupa",
"dziwka",
"ejackulate",
"Ekrem",
"Ekto",
"enculer",
"faen",
"fag",
"fanculo",
"fanny",
"feces",
"feg",
"Felcher",
"ficken",
"fitt",
"Flikker",
"foreskin",
"Fotze",
"futkretzn",
"gay",
"gook",
"guiena",
"h0r",
"h4x0r",
"hell",
"helvete",
"hoer",
"honkey",
"Huevon",
"hui",
"injun",
"jizz",
"kanker",
"kike",
"klootzak",
"kraut",
"knulle",
"kuk",
"kuksuger",
"Kurac",
"kurwa",
"kusi",
"kyrpa",
"lesbo",
"mamhoon",
"masturbat",
"merd",
"mibun",
"monkleigh",
"mouliewop",
"muie",
"mulkku",
"muschi",
"nazis",
"nepesaurio",
"nigger",
"orospu",
"paska",
"perse",
"picka",
"pierdol",
"pillu",
"pimmel",
"piss",
"pizda",
"poontsee",
"poop",
"porn",
"p0rn",
"pr0n",
"preteen",
"pula",
"pule",
"puta",
"puto",
"qahbeh",
"queef",
"rautenberg",
"schaffer",
"scheiss",
"schlampe",
"schmuck",
"screw",
"sh!t",
"sharmuta",
"sharmute",
"shipal",
"shiz",
"skribz",
"skurwysyn",
"sphencter",
"spic",
"spierdalaj",
"splooge",
"suka",
"b00b",
"testicle",
"titt",
"twat",
"vittu",
"wank",
"wetback",
"wichser",
"zabourah"]

