application: andfridge 
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images 
- url: /js
  static_dir: js 
- url: /.*
  script: andfridge.app

libraries:
- name: jinja2
  version: latest
